### ISSUE TITLE
Start script not found in the package.json of the root directory

### ISSUE THREAD

**Issue by aliraza944** [automatarium/automatarium#133]
According to the README.md  file, after installing all the dependencies using `yarn install`  you need to run `yarn start` to run the server, but no **start script** is present in the package.json file so it gives you an error.

**Comment by giraugh** [comment]
Hi @aliraza944, thanks for your interest in this project. Currently we don't quite have everything setup for external contributions. Notably, we have dependencies on mongodb and firebase that aren't fully documented. You are welcome to read over and reference any code however.

If you are feeling *very* dedicated, you can setup a mongodb database and firebase project. Then create a `.env` file in the backend directory as per the sample that references that database. Finally, export the firebase service account JSON and also reference that in the backend `.env`.

As for the specific content of your issue, thanks for pointing that out. The README hasn't been updated since we moved to using `yarn` workspaces. You should be able to navigate to the root of the repository and run `yarn dev` to concurrently run each service.
