### ISSUE TITLE
Comment Modals not being consistent

### ISSUE THREAD

**Issue by LvandoApps** [automatarium/automatarium#271]
Plenty of problems with comment modals, should be a comment with an enter button and actual "enter" functionality (i.e can press enter or press the button to confirm). FSA is closest to being correct, but all of them need to be corrected.

**Comment by tdib** [comment]
FSAs: Need return icon
PDAs: Completely jank
TMs: Reuse modal from transitions (completely jank)

**Comment by ire4ever1190** [comment]
TMs: Caused by this `if` statement which makes it always return the transition modal
https://github.com/automatarium/automatarium/blob/56feb729b3b8a33f6d48101cc0480f8849322dc9/frontend/src/components/InputDialogs/InputDialogs.js#L198
PDAs: There are `if` statements (in the `else` case of the statement linked before)  that check if the project is PDA and then adds PDA's extra lines

Fix looks like checking `if (dialog.type === 'comment')` before anything else and then returning a comment specific modal

**Comment by LvandoApps** [comment]
I'll handle it 👍
