### ISSUE TITLE
Project renaming does not save if project is exited quickly

### ISSUE THREAD

**Issue by SidhraFernando-Plant** [automatarium/automatarium#286]
When the name is changed while working on a project, the name persists in the window but if you navigate to the home screen too quickly the new name is not saved.

**Comment by ire4ever1190** [comment]
Project renaming seems to work, but you need to wait inside the project for a bit of time for the saving to work.

Maybe saving should be faster? Atleast when saving to browser storage

**Comment by SidhraFernando-Plant** [comment]
A progress bar could also do the trick, to make sure you don't exit before its fully saved (and it can just follow an arbitrary amount of time that allows for a safe save). Or some kind of pop up if you try and exit before it's saved. But yeah would be good to make it faster if possible

**Comment by LvandoApps** [comment]
Either what Sidi suggested, or what Jake suggested with the speed (this should be the first thing to check). Otherwise an alternative to Sidi's is making it possible to go outside the project, but the saving takes place in the background, sort of like how an auto-save in a video game works. This can be discussed if the speed can't be fixed.
