### ISSUE TITLE
Right click on transition arrow not working

### ISSUE THREAD

**Issue by SidhraFernando-Plant** [automatarium/automatarium#398]
### Description of the bug

There is a transition-specific right click menu, it currently only comes up if you right click on the label of the transition. It won't come up if you right click the arrow itself.
<img width="613" alt="Screen Shot 2023-06-13 at 7 39 45 pm" src="https://github.com/automatarium/automatarium/assets/79517325/32d3aeaf-5ba4-41cf-a665-3c1589c5d229">

### To reproduce

1. Be in project of any type
2. Right click on transition (arrow part specifically)
3. Transition edit/delete menu doesn't come up

### Expected behavior

The transition right click menu (with edit and delete options) should also come up when the arrow part of the transition is clicked (as well as when the label is clicked which is what currently happens, this should not be changed).

**Comment by ire4ever1190** [comment]
Ah I remember this now.
Because of #342 the edge corresponds to multiple transitions so you cant right click the edge anymore to get the context menu for the transition

Future groups could support this by mimicking JFLAP in that double clicking the edge will edit the first transition. Implementation would go somewhere around here
https://github.com/automatarium/automatarium/blob/a627642210a95bad2dce27d7aa60a39d452922f2/frontend/src/components/TransitionSet/TransitionSet.tsx#L173-L179
