### ISSUE TITLE
Sign up not working

### ISSUE THREAD

**Issue by anioncat** [automatarium/automatarium#408]
### Description of the bug

![20230806-153905_firefox5YTXPbmt_504x516](https://github.com/automatarium/automatarium/assets/82514325/4b089dc6-7606-48ab-8e20-d6cd04841c83)

### To reproduce

1. Click on start building
2. Click on sign up
3. Enter details

### Expected behavior

Sign up should create an account without an unknown error.

### Additional information

Local build also does not work via `yarn dev` as the backend requires a firebase account config which is not documented. (Is there someone we can contact for that?)

With this issue we should also fix any (if any) issues with the frontend communicating with the backend.

**Comment by tdib** [comment]
Not sure if you've discussed this with the previous team at all but I believe the backend has essentially been nuked so this functionality is redundant at this point (if there actually is no backend). I suppose if you wanted you could go ahead and reimplement it or rethink it - The general idea originally was to have a convenient method to share projects via a link with one another rather than having to export a file or anything like that.
