### ISSUE TITLE
Add manual stepping option for turing machines in testing lab

### ISSUE THREAD

**Issue by s3782534** [automatarium/automatarium#475]
### Proposed feature or solution

Currently, the testing lab only shows the tape that resulted of the first found successful execution path of the machine from the given input tape.  With a deterministic turing machine, there would only ever be one possible output tape for a given input tape, however with non-determinism there may be multiple possible output tapes. While the current way things are would work when testing for if a non-deterministic turing machine halts successfully, there may be times where the user may want to see multiple possible output tapes, which cannot currently be done.

The proposition is to add an option to the "trace" section of the testing lab to allow for manual stepping, where the user can select which transition to take when there are multiple options available. This would aid the user in exploring different paths that can be taken and seeing the different output tapes that can be produced by a given input tape.

### Alternatives

An option to see if a given output tape could be produced by a turing machine & input tape could also work for some use-cases, however if working with a non-deterministic turing machine it may take a long time to search through all possible outputs.

### Additional information

![pin_guesser_scr](https://github.com/automatarium/automatarium/assets/49254194/cfc0a5f7-05a2-4339-9cc6-596c019dc1a2)

Here is a simple non-deterministic turing machine that replaces all x's of the input tape with a number. Currently, when running in the testing lab it only ever shows 0s in the output tape, despite any combination of numbers being possible. If this enhancement was implemented, it would be possible to manually select the transitions to see if a given number combination is possible.

**Comment by s3897720** [comment]
I get the feeling (as per our discussion) this is related to and/or solves #465 in terms of outcome - the current/old (depending on how much work has been done on the sim up to now) setup as I understand it is "determine one way that the machine can succeed" via breadth-first search.

As per our separate work discussed today, I have a mockup of the GUI side of things for this, which I can start working on in the next week or so (I'll put it below so that if we can't complete this for whatever reason there's documentation for the next group :tm:

![Untitled Diagram drawio](https://github.com/automatarium/automatarium/assets/103556103/7d976ce8-2f4f-4c80-932b-62eec90c8186)
